title: Linzhe Jiang's Homepage
page-top-title: Linzhe Jiang
top-section-bg-text: Surgery Vision
home-subtitle: Linzhe Jiang&ensp;|&ensp;姜麟哲
copyright-text: '&copy; Linzhe Jiang 2023-2024. All Rights Reserved.'
